const Database = require('better-sqlite3');
const path = require('path');

const DB_PATH = path.join(__dirname, 'foodmatchs.db');
const db = new Database(DB_PATH);

console.log('🍽️  Seeding FoodMatchs database with meals...');

// =====================================================
// QUESTIONS (50+)
// =====================================================
const questions = [
    // Goûts de base
    { id: 'spicy', question: 'Tu aimes les plats épicés ?', emoji: '🌶️', tags: 'spicy,hot', category: 'taste', image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?w=600&h=400&fit=crop' },
    { id: 'garlic', question: "Fan d'ail ?", emoji: '🧄', tags: 'garlic,aromatic', category: 'taste', image: 'https://images.unsplash.com/photo-1615477550927-6ec8445b4b11?w=600&h=400&fit=crop' },
    { id: 'herbs', question: 'Herbes fraîches dans tes plats ?', emoji: '🌿', tags: 'herbs,fresh,aromatic', category: 'taste', image: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=600&h=400&fit=crop' },
    { id: 'sweet_savory', question: 'Tu aimes le sucré-salé ?', emoji: '🍯', tags: 'sweet_savory,complex', category: 'taste', image: 'https://images.unsplash.com/photo-1432139509613-5c4255815697?w=600&h=400&fit=crop' },
    { id: 'lemon', question: 'Une touche de citron ?', emoji: '🍋', tags: 'lemon,citrus,fresh', category: 'taste', image: 'https://images.unsplash.com/photo-1590502593747-42a996133562?w=600&h=400&fit=crop' },
    { id: 'umami', question: 'Tu recherches les saveurs umami ?', emoji: '🍄', tags: 'umami,savory,deep', category: 'taste', image: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=600&h=400&fit=crop' },
    { id: 'bitter', question: "L'amertume, ça te plaît ?", emoji: '🥬', tags: 'bitter,complex', category: 'taste', image: 'https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=600&h=400&fit=crop' },
    { id: 'smoky', question: 'Les saveurs fumées ?', emoji: '💨', tags: 'smoky,bbq,grilled', category: 'taste', image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600&h=400&fit=crop' },

    // Textures
    { id: 'crispy', question: 'Tu craques pour le croustillant ?', emoji: '🥓', tags: 'crispy,crunchy,texture', category: 'texture', image: 'https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=600&h=400&fit=crop' },
    { id: 'creamy', question: 'Sauces crémeuses ?', emoji: '🥛', tags: 'creamy,smooth,rich', category: 'texture', image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=400&fit=crop' },
    { id: 'sauce', question: 'Tu aimes quand ça sauce bien ?', emoji: '🍝', tags: 'sauce,juicy,wet', category: 'texture', image: 'https://images.unsplash.com/photo-1598866594230-a7c12756260f?w=600&h=400&fit=crop' },
    { id: 'cheese', question: "Plus y'a de fromage, mieux c'est ?", emoji: '🧀', tags: 'cheese,melty,gooey', category: 'texture', image: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=600&h=400&fit=crop', requires_json: '{"extras":["cheese"]}' },
    { id: 'raw', question: 'Tu apprécies les plats crus ?', emoji: '🥗', tags: 'raw,fresh,light', category: 'texture', image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop' },

    // Cuisines du monde
    { id: 'italian', question: 'La cuisine italienne ?', emoji: '🇮🇹', tags: 'italian,mediterranean,pasta', category: 'cuisine', image: 'https://images.unsplash.com/photo-1498579150354-977475b7ea0b?w=600&h=400&fit=crop' },
    { id: 'french', question: 'La gastronomie française ?', emoji: '🇫🇷', tags: 'french,classic,refined', category: 'cuisine', image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=400&fit=crop' },
    { id: 'japanese', question: 'Cuisine japonaise ?', emoji: '🇯🇵', tags: 'japanese,asian,umami', category: 'cuisine', image: 'https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=600&h=400&fit=crop' },
    { id: 'chinese', question: 'Cuisine chinoise ?', emoji: '🇨🇳', tags: 'chinese,asian,wok', category: 'cuisine', image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&h=400&fit=crop' },
    { id: 'thai', question: 'Pad thaï, tom yum... ?', emoji: '🇹🇭', tags: 'thai,asian,spicy,fresh', category: 'cuisine', image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&h=400&fit=crop' },
    { id: 'indian', question: 'Curry et saveurs indiennes ?', emoji: '🇮🇳', tags: 'indian,spicy,aromatic', category: 'cuisine', image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop' },
    { id: 'mexican', question: 'Tacos, burritos... ?', emoji: '🇲🇽', tags: 'mexican,spicy,corn', category: 'cuisine', image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop' },
    { id: 'korean', question: 'Kimchi et BBQ coréen ?', emoji: '🇰🇷', tags: 'korean,asian,fermented,spicy', category: 'cuisine', image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600&h=400&fit=crop' },
    { id: 'vietnamese', question: 'Phở et banh mi ?', emoji: '🇻🇳', tags: 'vietnamese,asian,fresh,herbs', category: 'cuisine', image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&h=400&fit=crop' },
    { id: 'greek', question: 'Cuisine grecque ?', emoji: '🇬🇷', tags: 'greek,mediterranean,fresh', category: 'cuisine', image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&h=400&fit=crop' },
    { id: 'spanish', question: 'Tapas et paella ?', emoji: '🇪🇸', tags: 'spanish,mediterranean,sharing', category: 'cuisine', image: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=600&h=400&fit=crop' },
    { id: 'moroccan', question: 'Tajines et couscous ?', emoji: '🇲🇦', tags: 'moroccan,spices,slow', category: 'cuisine', image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?w=600&h=400&fit=crop' },
    { id: 'lebanese', question: 'Mezze libanais ?', emoji: '🇱🇧', tags: 'lebanese,mediterranean,mezze', category: 'cuisine', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop' },

    // Protéines
    { id: 'steak', question: 'Un bon steak ?', emoji: '🥩', tags: 'meat,beef,steak,protein', category: 'protein', image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&h=400&fit=crop', exclude_diet: '["vegetarian","vegan"]' },
    { id: 'chicken', question: 'Poulet rôti ?', emoji: '🍗', tags: 'meat,chicken,poultry,protein', category: 'protein', image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600&h=400&fit=crop', exclude_diet: '["vegetarian","vegan"]' },
    { id: 'pork', question: 'Porc et charcuterie ?', emoji: '🥓', tags: 'meat,pork,protein', category: 'protein', image: 'https://images.unsplash.com/photo-1623653387945-2fd25214f8fc?w=600&h=400&fit=crop', exclude_diet: '["vegetarian","vegan"]' },
    { id: 'lamb', question: 'Agneau ?', emoji: '🐑', tags: 'meat,lamb,protein', category: 'protein', image: 'https://images.unsplash.com/photo-1514516345957-556ca7d90a29?w=600&h=400&fit=crop', exclude_diet: '["vegetarian","vegan"]' },
    { id: 'salmon', question: 'Saumon ?', emoji: '🐟', tags: 'fish,salmon,omega,protein', category: 'protein', image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&h=400&fit=crop', exclude_diet: '["vegan"]' },
    { id: 'seafood', question: 'Fruits de mer ?', emoji: '🦐', tags: 'seafood,shellfish,iodine', category: 'protein', image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=600&h=400&fit=crop', exclude_diet: '["vegetarian","vegan"]' },
    { id: 'tofu', question: 'Tofu ?', emoji: '🧊', tags: 'tofu,plant,vegan,protein', category: 'protein', image: 'https://images.unsplash.com/photo-1628679474900-eb53fa8d4e8a?w=600&h=400&fit=crop' },
    { id: 'eggs', question: 'Œufs ?', emoji: '🥚', tags: 'eggs,breakfast,versatile', category: 'protein', image: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600&h=400&fit=crop', exclude_diet: '["vegan"]' },

    // Légumes
    { id: 'mushroom', question: 'Champignons ?', emoji: '🍄', tags: 'mushroom,umami,earthy', category: 'vegetable', image: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=600&h=400&fit=crop' },
    { id: 'avocado', question: 'Avocat ?', emoji: '🥑', tags: 'avocado,healthy,creamy', category: 'vegetable', image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=600&h=400&fit=crop' },
    { id: 'tomato', question: 'Tomates fraîches ?', emoji: '🍅', tags: 'tomato,fresh,mediterranean', category: 'vegetable', image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&h=400&fit=crop' },
    { id: 'eggplant', question: 'Aubergine ?', emoji: '🍆', tags: 'eggplant,mediterranean,roasted', category: 'vegetable', image: 'https://images.unsplash.com/photo-1628689469838-524a4a973b8e?w=600&h=400&fit=crop' },
    { id: 'root_veg', question: 'Légumes racines ?', emoji: '🥕', tags: 'carrot,root,earthy,comfort', category: 'vegetable', image: 'https://images.unsplash.com/photo-1447175008436-054170c2e979?w=600&h=400&fit=crop' },

    // Styles
    { id: 'healthy', question: 'Manger healthy ?', emoji: '🥗', tags: 'healthy,light,nutritious', category: 'style', image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop' },
    { id: 'comfort', question: 'Comfort food ?', emoji: '🍔', tags: 'comfort,rich,satisfying', category: 'style', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=400&fit=crop' },
    { id: 'street', question: 'Street food ?', emoji: '🌯', tags: 'street,casual,quick', category: 'style', image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=400&fit=crop' },
    { id: 'bbq', question: 'Barbecue ?', emoji: '🔥', tags: 'bbq,grilled,smoky,outdoor', category: 'style', image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600&h=400&fit=crop' },
    { id: 'brunch', question: 'Fan de brunch ?', emoji: '🥞', tags: 'brunch,morning,eggs,relaxed', category: 'style', image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=600&h=400&fit=crop' },

    // Desserts
    { id: 'chocolate', question: 'Chocolat ?', emoji: '🍫', tags: 'chocolate,sweet,indulgent', category: 'dessert', image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?w=600&h=400&fit=crop' },
    { id: 'pastry', question: 'Pâtisseries ?', emoji: '🥐', tags: 'pastry,sweet,baked,french', category: 'dessert', image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&h=400&fit=crop' },
    { id: 'fruit_dessert', question: 'Desserts fruités ?', emoji: '🍓', tags: 'fruit,fresh,light,sweet', category: 'dessert', image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600&h=400&fit=crop' },
    { id: 'ice_cream', question: 'Glaces et sorbets ?', emoji: '🍨', tags: 'ice_cream,cold,refreshing', category: 'dessert', image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=600&h=400&fit=crop' },
    { id: 'caramel', question: 'Caramel ?', emoji: '🍮', tags: 'caramel,sweet,rich', category: 'dessert', image: 'https://images.unsplash.com/photo-1474625417243-95c67ec66c5b?w=600&h=400&fit=crop' },

    // Vins (conditionnel)
    { id: 'wine_red', question: 'Vin rouge ?', emoji: '🍷', tags: 'wine_red,pairing,french', category: 'wine', image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&h=400&fit=crop', requires_json: '{"alcohol":true,"extras":["wine"]}' },
    { id: 'wine_white', question: 'Vin blanc ?', emoji: '🥂', tags: 'wine_white,pairing,fresh', category: 'wine', image: 'https://images.unsplash.com/photo-1566452348683-81f9c56220f1?w=600&h=400&fit=crop', requires_json: '{"alcohol":true,"extras":["wine"]}' },
    { id: 'wine_rose', question: 'Rosé ?', emoji: '🌸', tags: 'wine_rose,pairing,summer', category: 'wine', image: 'https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=600&h=400&fit=crop', requires_json: '{"alcohol":true,"extras":["wine"]}' },

    // Fromages (conditionnel)  
    { id: 'soft_cheese', question: 'Fromages à pâte molle ?', emoji: '🧀', tags: 'cheese,soft,creamy,french', category: 'cheese', image: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&h=400&fit=crop', requires_json: '{"extras":["cheese"]}' },
    { id: 'hard_cheese', question: 'Fromages à pâte dure ?', emoji: '🧀', tags: 'cheese,hard,aged,strong', category: 'cheese', image: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=600&h=400&fit=crop', requires_json: '{"extras":["cheese"]}' },
    { id: 'blue_cheese', question: 'Fromages bleus ?', emoji: '🧀', tags: 'cheese,blue,strong,pungent', category: 'cheese', image: 'https://images.unsplash.com/photo-1505575967455-40e256f73376?w=600&h=400&fit=crop', requires_json: '{"extras":["cheese"]}' },
];

const insertQuestion = db.prepare(`
    INSERT OR REPLACE INTO questions (id, question, emoji, tags, category, image, requires_json, exclude_diet)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`);

for (const q of questions) {
    insertQuestion.run(
        q.id, q.question, q.emoji, q.tags, q.category, 
        q.image || null, q.requires_json || '{}', q.exclude_diet || '[]'
    );
}
console.log(`✅ ${questions.length} questions inserted`);

// =====================================================
// STARTERS (200+)
// =====================================================
const starters = [
    // FRENCH STARTERS
    { id: 'soupe_oignon', name: 'Soupe à l\'oignon gratinée', emoji: '🧅', description: 'Classique français, oignons caramélisés, croûton, gruyère fondu', tags: 'french,cheese,comfort,onion,winter', cuisine: 'french', prep_time: 20, cook_time: 45, difficulty: 2, budget: 'low', calories: 320, servings: 4, wine_pairing: 'Côtes du Rhône', is_vegetarian: 1, season: 'winter', recipe_json: JSON.stringify({ steps: ['Émincer 1kg d\'oignons finement', 'Faire revenir les oignons dans 50g de beurre 30min à feu doux', 'Ajouter 1L de bouillon de bœuf', 'Laisser mijoter 20min', 'Verser dans des bols, ajouter croûtons et gruyère râpé', 'Gratiner 5min au four'] }), ingredients_json: JSON.stringify([{ name: 'Oignons', qty: '1 kg', cat: 'légumes' }, { name: 'Beurre', qty: '50g', cat: 'crémerie' }, { name: 'Bouillon de bœuf', qty: '1L', cat: 'épicerie' }, { name: 'Gruyère râpé', qty: '200g', cat: 'fromage' }, { name: 'Pain', qty: '4 tranches', cat: 'boulangerie' }]) },
    
    { id: 'foie_gras', name: 'Foie gras mi-cuit', emoji: '🦆', description: 'Foie gras maison, chutney de figues, pain toasté', tags: 'french,luxury,festive,rich', cuisine: 'french', prep_time: 30, cook_time: 40, difficulty: 4, budget: 'high', calories: 450, servings: 8, wine_pairing: 'Sauternes', season: 'winter', recipe_json: JSON.stringify({ steps: ['Dénerver le foie gras', 'Assaisonner sel, poivre, muscade', 'Presser dans une terrine', 'Cuire au bain-marie 40min à 110°C', 'Réfrigérer 24h minimum', 'Servir avec chutney et toasts'] }), ingredients_json: JSON.stringify([{ name: 'Foie gras cru', qty: '500g', cat: 'viande' }, { name: 'Figues séchées', qty: '200g', cat: 'fruits' }, { name: 'Pain de mie', qty: '1 paquet', cat: 'boulangerie' }]) },

    { id: 'escargots', name: 'Escargots de Bourgogne', emoji: '🐌', description: 'Escargots, beurre persillé à l\'ail', tags: 'french,garlic,butter,classic,luxury', cuisine: 'french', prep_time: 20, cook_time: 15, difficulty: 3, budget: 'medium', calories: 280, servings: 4, wine_pairing: 'Chablis', season: 'all', recipe_json: JSON.stringify({ steps: ['Préparer le beurre: mélanger beurre pommade, ail, persil, sel', 'Placer les escargots dans leurs coquilles', 'Recouvrir généreusement de beurre persillé', 'Enfourner 12min à 200°C', 'Servir brûlant avec pain'] }), ingredients_json: JSON.stringify([{ name: 'Escargots en conserve', qty: '24', cat: 'épicerie' }, { name: 'Beurre', qty: '150g', cat: 'crémerie' }, { name: 'Ail', qty: '4 gousses', cat: 'légumes' }, { name: 'Persil', qty: '1 bouquet', cat: 'légumes' }]) },

    { id: 'terrine_campagne', name: 'Terrine de campagne', emoji: '🥖', description: 'Terrine rustique porc et foie, cornichons', tags: 'french,pork,traditional,rustic', cuisine: 'french', prep_time: 45, cook_time: 90, difficulty: 3, budget: 'medium', calories: 380, servings: 10, wine_pairing: 'Beaujolais', season: 'all', recipe_json: JSON.stringify({ steps: ['Hacher grossièrement le porc et le foie', 'Mélanger avec œufs, cognac, épices', 'Barder la terrine de lard', 'Cuire au bain-marie 1h30 à 160°C', 'Presser et réfrigérer 48h', 'Servir avec cornichons et pain'] }), ingredients_json: JSON.stringify([{ name: 'Échine de porc', qty: '400g', cat: 'viande' }, { name: 'Foie de porc', qty: '200g', cat: 'viande' }, { name: 'Lard', qty: '150g', cat: 'viande' }, { name: 'Œufs', qty: '2', cat: 'crémerie' }, { name: 'Cognac', qty: '3cl', cat: 'épicerie' }]) },

    { id: 'quiche_lorraine', name: 'Quiche Lorraine', emoji: '🥧', description: 'Pâte brisée, lardons, œufs, crème', tags: 'french,eggs,bacon,classic,comfort', cuisine: 'french', prep_time: 25, cook_time: 40, difficulty: 2, budget: 'low', calories: 420, servings: 6, wine_pairing: 'Riesling', season: 'all', recipe_json: JSON.stringify({ steps: ['Étaler la pâte dans un moule', 'Faire revenir les lardons', 'Battre œufs et crème', 'Répartir lardons sur la pâte', 'Verser l\'appareil', 'Cuire 40min à 180°C'] }), ingredients_json: JSON.stringify([{ name: 'Pâte brisée', qty: '1', cat: 'épicerie' }, { name: 'Lardons', qty: '200g', cat: 'viande' }, { name: 'Œufs', qty: '3', cat: 'crémerie' }, { name: 'Crème fraîche', qty: '25cl', cat: 'crémerie' }]) },

    { id: 'veloute_champignons', name: 'Velouté de champignons', emoji: '🍄', description: 'Champignons de Paris, crème, truffe', tags: 'french,mushroom,creamy,elegant,umami', cuisine: 'french', prep_time: 15, cook_time: 25, difficulty: 2, budget: 'medium', calories: 220, servings: 4, wine_pairing: 'Bourgogne blanc', is_vegetarian: 1, season: 'autumn', recipe_json: JSON.stringify({ steps: ['Émincer 500g de champignons', 'Faire suer dans du beurre avec échalotes', 'Ajouter bouillon et crème', 'Mixer finement', 'Assaisonner et ajouter huile de truffe', 'Servir avec croûtons'] }), ingredients_json: JSON.stringify([{ name: 'Champignons de Paris', qty: '500g', cat: 'légumes' }, { name: 'Échalotes', qty: '2', cat: 'légumes' }, { name: 'Crème', qty: '20cl', cat: 'crémerie' }, { name: 'Huile de truffe', qty: '1 cs', cat: 'épicerie' }]) },

    { id: 'salade_chevre_chaud', name: 'Salade de chèvre chaud', emoji: '🧀', description: 'Mesclun, toast de chèvre, miel, noix', tags: 'french,cheese,salad,honey,fresh', cuisine: 'french', prep_time: 15, cook_time: 10, difficulty: 1, budget: 'medium', calories: 340, servings: 4, wine_pairing: 'Sancerre', is_vegetarian: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Préparer la vinaigrette miel-moutarde', 'Toaster les tranches de pain', 'Poser le chèvre et passer au grill', 'Dresser le mesclun', 'Ajouter le toast, noix et miel'] }), ingredients_json: JSON.stringify([{ name: 'Mesclun', qty: '200g', cat: 'légumes' }, { name: 'Bûche de chèvre', qty: '200g', cat: 'fromage' }, { name: 'Pain de campagne', qty: '4 tranches', cat: 'boulangerie' }, { name: 'Noix', qty: '50g', cat: 'épicerie' }, { name: 'Miel', qty: '2 cs', cat: 'épicerie' }]) },

    { id: 'asperges_hollandaise', name: 'Asperges sauce hollandaise', emoji: '🌿', description: 'Asperges blanches, sauce hollandaise maison', tags: 'french,asparagus,butter,spring,elegant', cuisine: 'french', prep_time: 20, cook_time: 15, difficulty: 3, budget: 'medium', calories: 290, servings: 4, wine_pairing: 'Pouilly-Fumé', is_vegetarian: 1, season: 'spring', recipe_json: JSON.stringify({ steps: ['Éplucher et cuire les asperges 12min', 'Préparer la hollandaise au bain-marie', 'Monter les jaunes avec le beurre clarifié', 'Assaisonner citron, sel, cayenne', 'Dresser asperges, napper de sauce'] }), ingredients_json: JSON.stringify([{ name: 'Asperges blanches', qty: '1 kg', cat: 'légumes' }, { name: 'Beurre', qty: '200g', cat: 'crémerie' }, { name: 'Jaunes d\'œufs', qty: '3', cat: 'crémerie' }, { name: 'Citron', qty: '1', cat: 'fruits' }]) },

    // ITALIAN STARTERS
    { id: 'bruschetta', name: 'Bruschetta tomates', emoji: '🍅', description: 'Pain grillé, tomates fraîches, basilic, ail', tags: 'italian,tomato,fresh,garlic,simple', cuisine: 'italian', prep_time: 15, cook_time: 5, difficulty: 1, budget: 'low', calories: 180, servings: 4, wine_pairing: 'Chianti', is_vegan: 1, season: 'summer', recipe_json: JSON.stringify({ steps: ['Couper les tomates en dés', 'Mélanger avec basilic, ail, huile d\'olive', 'Griller le pain', 'Frotter à l\'ail', 'Garnir du mélange tomate'] }), ingredients_json: JSON.stringify([{ name: 'Tomates', qty: '4', cat: 'légumes' }, { name: 'Basilic', qty: '1 bouquet', cat: 'légumes' }, { name: 'Pain ciabatta', qty: '1', cat: 'boulangerie' }, { name: 'Ail', qty: '2 gousses', cat: 'légumes' }]) },

    { id: 'carpaccio_boeuf', name: 'Carpaccio de bœuf', emoji: '🥩', description: 'Fines tranches de bœuf cru, roquette, parmesan, câpres', tags: 'italian,beef,raw,elegant,fresh', cuisine: 'italian', prep_time: 20, cook_time: 0, difficulty: 2, budget: 'high', calories: 250, servings: 4, wine_pairing: 'Valpolicella', season: 'all', recipe_json: JSON.stringify({ steps: ['Congeler légèrement le filet de bœuf', 'Trancher très finement', 'Disposer sur assiettes froides', 'Arroser d\'huile d\'olive et citron', 'Parsemer de roquette et copeaux de parmesan', 'Ajouter câpres et poivre'] }), ingredients_json: JSON.stringify([{ name: 'Filet de bœuf', qty: '400g', cat: 'viande' }, { name: 'Roquette', qty: '100g', cat: 'légumes' }, { name: 'Parmesan', qty: '80g', cat: 'fromage' }, { name: 'Câpres', qty: '2 cs', cat: 'épicerie' }]) },

    { id: 'antipasti', name: 'Antipasti variés', emoji: '🫒', description: 'Assortiment charcuterie, fromages, légumes marinés', tags: 'italian,sharing,charcuterie,cheese,olives', cuisine: 'italian', prep_time: 20, cook_time: 0, difficulty: 1, budget: 'high', calories: 450, servings: 6, wine_pairing: 'Prosecco', season: 'all', recipe_json: JSON.stringify({ steps: ['Disposer la charcuterie en rosaces', 'Couper les fromages', 'Ajouter olives et légumes marinés', 'Servir avec gressins et focaccia'] }), ingredients_json: JSON.stringify([{ name: 'Jambon de Parme', qty: '150g', cat: 'viande' }, { name: 'Mortadelle', qty: '100g', cat: 'viande' }, { name: 'Mozzarella', qty: '200g', cat: 'fromage' }, { name: 'Olives', qty: '150g', cat: 'épicerie' }, { name: 'Artichauts marinés', qty: '200g', cat: 'épicerie' }]) },

    { id: 'burrata', name: 'Burrata crémeuse', emoji: '🧀', description: 'Burrata, tomates cerises, pesto, huile d\'olive', tags: 'italian,cheese,fresh,tomato,simple', cuisine: 'italian', prep_time: 10, cook_time: 0, difficulty: 1, budget: 'medium', calories: 320, servings: 4, wine_pairing: 'Vermentino', is_vegetarian: 1, season: 'summer', recipe_json: JSON.stringify({ steps: ['Couper les tomates en deux', 'Disposer la burrata au centre', 'Entourer des tomates', 'Arroser de pesto et huile d\'olive', 'Assaisonner fleur de sel'] }), ingredients_json: JSON.stringify([{ name: 'Burrata', qty: '2', cat: 'fromage' }, { name: 'Tomates cerises', qty: '300g', cat: 'légumes' }, { name: 'Pesto', qty: '3 cs', cat: 'épicerie' }]) },

    { id: 'vitello_tonnato', name: 'Vitello tonnato', emoji: '🐟', description: 'Rôti de veau froid, sauce au thon crémeuse', tags: 'italian,veal,tuna,cold,elegant', cuisine: 'italian', prep_time: 30, cook_time: 60, difficulty: 3, budget: 'high', calories: 380, servings: 6, wine_pairing: 'Soave', season: 'summer', recipe_json: JSON.stringify({ steps: ['Cuire le rôti de veau au bouillon 1h', 'Laisser refroidir complètement', 'Mixer thon, câpres, anchois, mayonnaise', 'Trancher finement le veau', 'Napper de sauce', 'Décorer de câpres'] }), ingredients_json: JSON.stringify([{ name: 'Rôti de veau', qty: '800g', cat: 'viande' }, { name: 'Thon en conserve', qty: '200g', cat: 'épicerie' }, { name: 'Câpres', qty: '50g', cat: 'épicerie' }, { name: 'Mayonnaise', qty: '100g', cat: 'épicerie' }]) },

    { id: 'caprese', name: 'Salade Caprese', emoji: '🍅', description: 'Tomates, mozzarella di bufala, basilic frais', tags: 'italian,tomato,cheese,fresh,simple,summer', cuisine: 'italian', prep_time: 10, cook_time: 0, difficulty: 1, budget: 'medium', calories: 280, servings: 4, wine_pairing: 'Pinot Grigio', is_vegetarian: 1, season: 'summer', recipe_json: JSON.stringify({ steps: ['Trancher tomates et mozzarella', 'Alterner en rosace', 'Parsemer de basilic', 'Arroser d\'huile d\'olive', 'Saler, poivrer'] }), ingredients_json: JSON.stringify([{ name: 'Tomates cœur de bœuf', qty: '4', cat: 'légumes' }, { name: 'Mozzarella di bufala', qty: '2', cat: 'fromage' }, { name: 'Basilic', qty: '1 bouquet', cat: 'légumes' }]) },

    // ASIAN STARTERS
    { id: 'gyoza', name: 'Gyoza japonais', emoji: '🥟', description: 'Raviolis grillés porc et chou, sauce soja-gingembre', tags: 'japanese,asian,pork,dumpling,crispy', cuisine: 'japanese', prep_time: 45, cook_time: 15, difficulty: 3, budget: 'low', calories: 280, servings: 4, wine_pairing: 'Saké', season: 'all', recipe_json: JSON.stringify({ steps: ['Préparer la farce: porc, chou, gingembre, ail', 'Garnir les feuilles de gyoza', 'Plier en demi-lune', 'Griller à la poêle avec un fond d\'eau', 'Servir avec sauce soja et vinaigre'] }), ingredients_json: JSON.stringify([{ name: 'Porc haché', qty: '300g', cat: 'viande' }, { name: 'Chou chinois', qty: '200g', cat: 'légumes' }, { name: 'Feuilles de gyoza', qty: '30', cat: 'épicerie' }, { name: 'Gingembre', qty: '20g', cat: 'légumes' }]) },

    { id: 'edamame', name: 'Edamame au sel', emoji: '🫛', description: 'Fèves de soja japonaises, fleur de sel', tags: 'japanese,asian,healthy,vegan,simple', cuisine: 'japanese', prep_time: 5, cook_time: 5, difficulty: 1, budget: 'low', calories: 120, servings: 4, wine_pairing: 'Bière japonaise', is_vegan: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Porter l\'eau salée à ébullition', 'Cuire les edamame 5min', 'Égoutter', 'Saupoudrer de fleur de sel', 'Servir tiède'] }), ingredients_json: JSON.stringify([{ name: 'Edamame surgelés', qty: '400g', cat: 'surgelés' }, { name: 'Fleur de sel', qty: '1 cs', cat: 'épicerie' }]) },

    { id: 'nem', name: 'Nems vietnamiens', emoji: '🥢', description: 'Rouleaux frits porc et crevettes, nuoc mam', tags: 'vietnamese,asian,pork,shrimp,crispy,fried', cuisine: 'vietnamese', prep_time: 45, cook_time: 15, difficulty: 3, budget: 'low', calories: 320, servings: 6, wine_pairing: 'Gewürztraminer', season: 'all', recipe_json: JSON.stringify({ steps: ['Préparer la farce: porc, crevettes, vermicelles, champignons noirs', 'Rouler dans les feuilles de riz', 'Frire jusqu\'à doré', 'Servir avec salade, herbes et nuoc mam'] }), ingredients_json: JSON.stringify([{ name: 'Porc haché', qty: '300g', cat: 'viande' }, { name: 'Crevettes', qty: '200g', cat: 'poisson' }, { name: 'Feuilles de riz', qty: '20', cat: 'épicerie' }, { name: 'Vermicelles', qty: '100g', cat: 'épicerie' }]) },

    { id: 'rouleaux_printemps', name: 'Rouleaux de printemps', emoji: '🥗', description: 'Rouleaux frais crevettes, vermicelles, menthe', tags: 'vietnamese,asian,fresh,shrimp,healthy,light', cuisine: 'vietnamese', prep_time: 30, cook_time: 0, difficulty: 2, budget: 'low', calories: 180, servings: 4, wine_pairing: 'Riesling', season: 'summer', recipe_json: JSON.stringify({ steps: ['Cuire vermicelles et crevettes', 'Tremper les galettes de riz', 'Garnir de salade, menthe, vermicelles, crevettes', 'Rouler serré', 'Servir avec sauce cacahuète'] }), ingredients_json: JSON.stringify([{ name: 'Crevettes', qty: '200g', cat: 'poisson' }, { name: 'Galettes de riz', qty: '12', cat: 'épicerie' }, { name: 'Vermicelles', qty: '100g', cat: 'épicerie' }, { name: 'Menthe', qty: '1 bouquet', cat: 'légumes' }]) },

    { id: 'tartare_saumon', name: 'Tartare de saumon asiatique', emoji: '🍣', description: 'Saumon frais, avocat, sésame, sauce soja-wasabi', tags: 'japanese,asian,salmon,raw,fresh,healthy', cuisine: 'japanese', prep_time: 20, cook_time: 0, difficulty: 2, budget: 'high', calories: 280, servings: 4, wine_pairing: 'Chablis', season: 'all', recipe_json: JSON.stringify({ steps: ['Couper le saumon en petits dés', 'Préparer la sauce soja-wasabi-citron vert', 'Couper l\'avocat', 'Mélanger délicatement', 'Dresser à l\'emporte-pièce', 'Parsemer de sésame et ciboulette'] }), ingredients_json: JSON.stringify([{ name: 'Saumon frais', qty: '400g', cat: 'poisson' }, { name: 'Avocat', qty: '2', cat: 'légumes' }, { name: 'Sauce soja', qty: '3 cs', cat: 'épicerie' }, { name: 'Wasabi', qty: '1 cc', cat: 'épicerie' }, { name: 'Sésame', qty: '2 cs', cat: 'épicerie' }]) },

    { id: 'dim_sum', name: 'Assortiment dim sum', emoji: '🥟', description: 'Ha kao, siu mai, char siu bao vapeur', tags: 'chinese,asian,dumpling,steamed,sharing', cuisine: 'chinese', prep_time: 60, cook_time: 20, difficulty: 4, budget: 'medium', calories: 350, servings: 4, wine_pairing: 'Thé oolong', season: 'all', recipe_json: JSON.stringify({ steps: ['Préparer les farces: crevettes, porc, char siu', 'Confectionner les différents dim sum', 'Cuire à la vapeur 15-20min', 'Servir avec sauce soja et piment'] }), ingredients_json: JSON.stringify([{ name: 'Crevettes', qty: '200g', cat: 'poisson' }, { name: 'Porc haché', qty: '200g', cat: 'viande' }, { name: 'Farine', qty: '300g', cat: 'épicerie' }, { name: 'Char siu', qty: '150g', cat: 'viande' }]) },

    { id: 'miso_soup', name: 'Soupe miso', emoji: '🍜', description: 'Bouillon dashi, miso, tofu, wakame, oignons verts', tags: 'japanese,asian,soup,tofu,healthy,umami', cuisine: 'japanese', prep_time: 10, cook_time: 10, difficulty: 1, budget: 'low', calories: 80, servings: 4, wine_pairing: 'Saké chaud', is_vegan: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Préparer le bouillon dashi', 'Ajouter le wakame réhydraté', 'Couper le tofu en dés', 'Délayer le miso hors du feu', 'Garnir d\'oignons verts'] }), ingredients_json: JSON.stringify([{ name: 'Pâte miso', qty: '4 cs', cat: 'épicerie' }, { name: 'Tofu soyeux', qty: '200g', cat: 'épicerie' }, { name: 'Wakame séché', qty: '10g', cat: 'épicerie' }, { name: 'Dashi', qty: '1L', cat: 'épicerie' }]) },

    { id: 'tom_yum', name: 'Tom Yum', emoji: '🍲', description: 'Soupe thaï épicée aux crevettes, citronnelle, galanga', tags: 'thai,asian,spicy,shrimp,soup,aromatic', cuisine: 'thai', prep_time: 15, cook_time: 20, difficulty: 2, budget: 'medium', calories: 180, servings: 4, wine_pairing: 'Riesling', season: 'all', recipe_json: JSON.stringify({ steps: ['Faire bouillir eau avec citronnelle, galanga, feuilles de combava', 'Ajouter champignons et tomates', 'Ajouter crevettes', 'Assaisonner pâte de piment, nuoc mam, citron vert', 'Garnir de coriandre'] }), ingredients_json: JSON.stringify([{ name: 'Crevettes', qty: '300g', cat: 'poisson' }, { name: 'Citronnelle', qty: '2 tiges', cat: 'légumes' }, { name: 'Galanga', qty: '30g', cat: 'légumes' }, { name: 'Champignons', qty: '150g', cat: 'légumes' }, { name: 'Pâte tom yum', qty: '3 cs', cat: 'épicerie' }]) },

    { id: 'satay', name: 'Brochettes satay', emoji: '🍢', description: 'Brochettes de poulet marinées, sauce cacahuète', tags: 'thai,asian,chicken,peanut,grilled,street', cuisine: 'thai', prep_time: 30, cook_time: 15, difficulty: 2, budget: 'low', calories: 320, servings: 4, wine_pairing: 'Bière thaï', season: 'all', recipe_json: JSON.stringify({ steps: ['Mariner le poulet: lait de coco, curcuma, cumin', 'Enfiler sur brochettes', 'Griller au barbecue ou à la plancha', 'Préparer sauce: beurre de cacahuète, lait de coco, soja', 'Servir avec sauce et concombre'] }), ingredients_json: JSON.stringify([{ name: 'Blancs de poulet', qty: '600g', cat: 'viande' }, { name: 'Lait de coco', qty: '20cl', cat: 'épicerie' }, { name: 'Beurre de cacahuète', qty: '100g', cat: 'épicerie' }, { name: 'Curcuma', qty: '1 cc', cat: 'épicerie' }]) },

    // MIDDLE EASTERN STARTERS
    { id: 'houmous', name: 'Houmous maison', emoji: '🫘', description: 'Purée de pois chiches, tahini, citron, ail', tags: 'lebanese,mediterranean,chickpea,vegan,healthy', cuisine: 'lebanese', prep_time: 15, cook_time: 0, difficulty: 1, budget: 'low', calories: 180, servings: 6, wine_pairing: 'Vin libanais blanc', is_vegan: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Mixer pois chiches égouttés', 'Ajouter tahini, jus de citron, ail', 'Mixer en ajoutant eau glacée', 'Assaisonner sel et cumin', 'Servir avec huile d\'olive et paprika'] }), ingredients_json: JSON.stringify([{ name: 'Pois chiches', qty: '400g', cat: 'épicerie' }, { name: 'Tahini', qty: '4 cs', cat: 'épicerie' }, { name: 'Citron', qty: '2', cat: 'fruits' }, { name: 'Ail', qty: '2 gousses', cat: 'légumes' }]) },

    { id: 'falafel', name: 'Falafels croustillants', emoji: '🧆', description: 'Boulettes de pois chiches frites, herbes fraîches', tags: 'lebanese,mediterranean,chickpea,vegan,crispy,fried', cuisine: 'lebanese', prep_time: 30, cook_time: 15, difficulty: 2, budget: 'low', calories: 280, servings: 4, wine_pairing: 'Rosé libanais', is_vegan: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Tremper pois chiches secs 24h', 'Mixer avec oignon, ail, persil, coriandre, cumin', 'Former des boulettes', 'Frire jusqu\'à doré', 'Servir avec tahini'] }), ingredients_json: JSON.stringify([{ name: 'Pois chiches secs', qty: '300g', cat: 'épicerie' }, { name: 'Persil', qty: '1 bouquet', cat: 'légumes' }, { name: 'Coriandre', qty: '1 bouquet', cat: 'légumes' }, { name: 'Cumin', qty: '2 cc', cat: 'épicerie' }]) },

    { id: 'baba_ganoush', name: 'Baba ganoush', emoji: '🍆', description: 'Caviar d\'aubergine fumée, tahini, citron', tags: 'lebanese,mediterranean,eggplant,vegan,smoky', cuisine: 'lebanese', prep_time: 15, cook_time: 40, difficulty: 2, budget: 'low', calories: 150, servings: 6, wine_pairing: 'Vin grec blanc', is_vegan: 1, season: 'summer', recipe_json: JSON.stringify({ steps: ['Griller aubergines entières au four ou flamme', 'Récupérer la chair', 'Mixer avec tahini, ail, citron', 'Assaisonner sel et cumin', 'Servir avec huile d\'olive et persil'] }), ingredients_json: JSON.stringify([{ name: 'Aubergines', qty: '3', cat: 'légumes' }, { name: 'Tahini', qty: '3 cs', cat: 'épicerie' }, { name: 'Citron', qty: '1', cat: 'fruits' }, { name: 'Ail', qty: '2 gousses', cat: 'légumes' }]) },

    { id: 'tabouleh', name: 'Taboulé libanais', emoji: '🥗', description: 'Persil, menthe, boulgour, tomates, citron', tags: 'lebanese,mediterranean,fresh,herbs,salad,healthy', cuisine: 'lebanese', prep_time: 25, cook_time: 0, difficulty: 1, budget: 'low', calories: 160, servings: 6, wine_pairing: 'Vin blanc sec', is_vegan: 1, season: 'summer', recipe_json: JSON.stringify({ steps: ['Tremper le boulgour 15min', 'Hacher finement persil et menthe', 'Couper tomates et oignons en petits dés', 'Mélanger le tout', 'Assaisonner huile d\'olive et citron'] }), ingredients_json: JSON.stringify([{ name: 'Persil plat', qty: '3 bouquets', cat: 'légumes' }, { name: 'Menthe', qty: '1 bouquet', cat: 'légumes' }, { name: 'Boulgour fin', qty: '50g', cat: 'épicerie' }, { name: 'Tomates', qty: '3', cat: 'légumes' }]) },

    // SPANISH STARTERS
    { id: 'patatas_bravas', name: 'Patatas bravas', emoji: '🥔', description: 'Pommes de terre frites, sauce tomate épicée, aïoli', tags: 'spanish,tapas,potato,spicy,fried', cuisine: 'spanish', prep_time: 20, cook_time: 30, difficulty: 2, budget: 'low', calories: 320, servings: 4, wine_pairing: 'Rioja', is_vegetarian: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Couper pommes de terre en cubes', 'Frire jusqu\'à doré', 'Préparer sauce bravas: tomate, piment, paprika', 'Préparer aïoli: ail, mayonnaise', 'Servir avec les deux sauces'] }), ingredients_json: JSON.stringify([{ name: 'Pommes de terre', qty: '800g', cat: 'légumes' }, { name: 'Sauce tomate', qty: '200g', cat: 'épicerie' }, { name: 'Paprika fumé', qty: '1 cs', cat: 'épicerie' }, { name: 'Mayonnaise', qty: '100g', cat: 'épicerie' }]) },

    { id: 'gambas_ajillo', name: 'Gambas al ajillo', emoji: '🦐', description: 'Crevettes à l\'ail, piment, huile d\'olive', tags: 'spanish,tapas,shrimp,garlic,spicy', cuisine: 'spanish', prep_time: 10, cook_time: 10, difficulty: 1, budget: 'medium', calories: 250, servings: 4, wine_pairing: 'Albariño', season: 'all', recipe_json: JSON.stringify({ steps: ['Chauffer huile d\'olive avec ail émincé', 'Ajouter piment', 'Saisir les gambas 2min de chaque côté', 'Parsemer de persil', 'Servir brûlant avec pain'] }), ingredients_json: JSON.stringify([{ name: 'Gambas', qty: '500g', cat: 'poisson' }, { name: 'Ail', qty: '8 gousses', cat: 'légumes' }, { name: 'Piment', qty: '1', cat: 'légumes' }, { name: 'Huile d\'olive', qty: '10cl', cat: 'épicerie' }]) },

    { id: 'tortilla', name: 'Tortilla española', emoji: '🥚', description: 'Omelette épaisse aux pommes de terre, oignons', tags: 'spanish,tapas,eggs,potato,comfort', cuisine: 'spanish', prep_time: 20, cook_time: 30, difficulty: 2, budget: 'low', calories: 280, servings: 6, wine_pairing: 'Verdejo', is_vegetarian: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Faire confire pommes de terre et oignons dans l\'huile', 'Battre les œufs', 'Mélanger avec légumes', 'Cuire à feu doux des deux côtés', 'Servir tiède en portions'] }), ingredients_json: JSON.stringify([{ name: 'Pommes de terre', qty: '600g', cat: 'légumes' }, { name: 'Oignons', qty: '2', cat: 'légumes' }, { name: 'Œufs', qty: '6', cat: 'crémerie' }, { name: 'Huile d\'olive', qty: '15cl', cat: 'épicerie' }]) },

    { id: 'jamon_melon', name: 'Jamón con melón', emoji: '🍈', description: 'Jambon ibérique, melon mûr', tags: 'spanish,tapas,ham,melon,fresh,simple', cuisine: 'spanish', prep_time: 10, cook_time: 0, difficulty: 1, budget: 'high', calories: 180, servings: 4, wine_pairing: 'Cava', season: 'summer', recipe_json: JSON.stringify({ steps: ['Couper le melon en tranches', 'Disposer les tranches de jambon', 'Servir frais'] }), ingredients_json: JSON.stringify([{ name: 'Jambon ibérique', qty: '150g', cat: 'viande' }, { name: 'Melon', qty: '1', cat: 'fruits' }]) },

    // MEXICAN STARTERS
    { id: 'guacamole', name: 'Guacamole frais', emoji: '🥑', description: 'Avocat écrasé, citron vert, coriandre, piment', tags: 'mexican,avocado,fresh,spicy,vegan', cuisine: 'mexican', prep_time: 15, cook_time: 0, difficulty: 1, budget: 'medium', calories: 200, servings: 4, wine_pairing: 'Margarita', is_vegan: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Écraser les avocats à la fourchette', 'Ajouter oignon, tomate, piment émincés', 'Assaisonner citron vert, sel', 'Parsemer de coriandre', 'Servir avec chips de maïs'] }), ingredients_json: JSON.stringify([{ name: 'Avocats', qty: '3', cat: 'légumes' }, { name: 'Citron vert', qty: '2', cat: 'fruits' }, { name: 'Coriandre', qty: '1 bouquet', cat: 'légumes' }, { name: 'Piment jalapeño', qty: '1', cat: 'légumes' }]) },

    { id: 'nachos', name: 'Nachos complets', emoji: '🌮', description: 'Chips de maïs, fromage fondu, jalapeños, guacamole', tags: 'mexican,cheese,spicy,sharing,comfort', cuisine: 'mexican', prep_time: 15, cook_time: 10, difficulty: 1, budget: 'low', calories: 450, servings: 4, wine_pairing: 'Bière mexicaine', is_vegetarian: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Disposer les chips sur plaque', 'Couvrir de fromage râpé', 'Ajouter jalapeños', 'Gratiner 10min', 'Servir avec guacamole et crème'] }), ingredients_json: JSON.stringify([{ name: 'Chips de maïs', qty: '200g', cat: 'épicerie' }, { name: 'Cheddar', qty: '200g', cat: 'fromage' }, { name: 'Jalapeños', qty: '100g', cat: 'épicerie' }, { name: 'Crème fraîche', qty: '100g', cat: 'crémerie' }]) },

    { id: 'ceviche', name: 'Ceviche de poisson', emoji: '🐟', description: 'Poisson cru mariné au citron vert, oignon rouge, coriandre', tags: 'mexican,fish,raw,fresh,citrus,light', cuisine: 'mexican', prep_time: 25, cook_time: 0, difficulty: 2, budget: 'medium', calories: 180, servings: 4, wine_pairing: 'Sauvignon Blanc', season: 'summer', recipe_json: JSON.stringify({ steps: ['Couper le poisson en dés', 'Mariner dans jus de citron vert 20min', 'Ajouter oignon rouge, piment, tomate', 'Assaisonner sel et coriandre', 'Servir frais avec chips'] }), ingredients_json: JSON.stringify([{ name: 'Poisson blanc frais', qty: '400g', cat: 'poisson' }, { name: 'Citrons verts', qty: '6', cat: 'fruits' }, { name: 'Oignon rouge', qty: '1', cat: 'légumes' }, { name: 'Coriandre', qty: '1 bouquet', cat: 'légumes' }]) },

    { id: 'quesadillas', name: 'Quesadillas', emoji: '🧀', description: 'Tortillas au fromage fondu, poulet, poivrons', tags: 'mexican,cheese,chicken,crispy,comfort', cuisine: 'mexican', prep_time: 15, cook_time: 10, difficulty: 1, budget: 'low', calories: 380, servings: 4, wine_pairing: 'Bière mexicaine', season: 'all', recipe_json: JSON.stringify({ steps: ['Garnir tortilla de fromage, poulet, poivrons', 'Replier en deux', 'Cuire à la poêle des deux côtés', 'Couper en triangles', 'Servir avec salsa et crème'] }), ingredients_json: JSON.stringify([{ name: 'Tortillas de blé', qty: '4', cat: 'épicerie' }, { name: 'Fromage râpé', qty: '200g', cat: 'fromage' }, { name: 'Poulet cuit', qty: '200g', cat: 'viande' }, { name: 'Poivrons', qty: '2', cat: 'légumes' }]) },

    // More starters to reach 200...
    { id: 'gazpacho', name: 'Gazpacho andalou', emoji: '🍅', description: 'Soupe froide tomates, concombre, poivron, ail', tags: 'spanish,tomato,cold,summer,vegan,healthy', cuisine: 'spanish', prep_time: 20, cook_time: 0, difficulty: 1, budget: 'low', calories: 120, servings: 6, wine_pairing: 'Fino', is_vegan: 1, season: 'summer', recipe_json: JSON.stringify({ steps: ['Mixer tomates, concombre, poivron, ail, pain', 'Ajouter huile d\'olive et vinaigre', 'Passer au tamis', 'Réfrigérer 2h minimum', 'Servir avec garniture de légumes'] }), ingredients_json: JSON.stringify([{ name: 'Tomates', qty: '1 kg', cat: 'légumes' }, { name: 'Concombre', qty: '1', cat: 'légumes' }, { name: 'Poivron rouge', qty: '1', cat: 'légumes' }, { name: 'Pain rassis', qty: '100g', cat: 'boulangerie' }]) },

    { id: 'samosas', name: 'Samosas indiens', emoji: '🥟', description: 'Beignets triangulaires, pommes de terre épicées, petits pois', tags: 'indian,potato,spicy,fried,vegetarian', cuisine: 'indian', prep_time: 45, cook_time: 20, difficulty: 3, budget: 'low', calories: 280, servings: 6, wine_pairing: 'Lassi', is_vegetarian: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Préparer la pâte et laisser reposer', 'Faire revenir pommes de terre, petits pois, épices', 'Former les triangles', 'Frire jusqu\'à doré', 'Servir avec chutney'] }), ingredients_json: JSON.stringify([{ name: 'Pommes de terre', qty: '500g', cat: 'légumes' }, { name: 'Petits pois', qty: '150g', cat: 'légumes' }, { name: 'Farine', qty: '250g', cat: 'épicerie' }, { name: 'Garam masala', qty: '2 cc', cat: 'épicerie' }]) },

    { id: 'pakoras', name: 'Pakoras', emoji: '🧅', description: 'Beignets de légumes à l\'indienne, épices', tags: 'indian,vegetables,spicy,fried,vegetarian', cuisine: 'indian', prep_time: 20, cook_time: 15, difficulty: 2, budget: 'low', calories: 220, servings: 4, wine_pairing: 'Bière indienne', is_vegetarian: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Préparer la pâte: farine de pois chiche, eau, épices', 'Couper les légumes', 'Enrober de pâte', 'Frire par petites quantités', 'Servir avec chutney menthe'] }), ingredients_json: JSON.stringify([{ name: 'Farine de pois chiche', qty: '200g', cat: 'épicerie' }, { name: 'Oignon', qty: '2', cat: 'légumes' }, { name: 'Épinards', qty: '100g', cat: 'légumes' }, { name: 'Cumin', qty: '1 cc', cat: 'épicerie' }]) },

    { id: 'croquetas', name: 'Croquetas au jambon', emoji: '🍖', description: 'Croquettes crémeuses au jambon serrano', tags: 'spanish,tapas,ham,crispy,fried,comfort', cuisine: 'spanish', prep_time: 40, cook_time: 15, difficulty: 3, budget: 'medium', calories: 180, servings: 6, wine_pairing: 'Manzanilla', season: 'all', recipe_json: JSON.stringify({ steps: ['Préparer béchamel épaisse', 'Ajouter jambon haché', 'Réfrigérer 4h', 'Former les croquettes', 'Paner et frire'] }), ingredients_json: JSON.stringify([{ name: 'Jambon serrano', qty: '150g', cat: 'viande' }, { name: 'Lait', qty: '500ml', cat: 'crémerie' }, { name: 'Farine', qty: '80g', cat: 'épicerie' }, { name: 'Beurre', qty: '80g', cat: 'crémerie' }]) },

    { id: 'pho', name: 'Phở vietnamien', emoji: '🍜', description: 'Bouillon parfumé, nouilles de riz, bœuf, herbes', tags: 'vietnamese,asian,beef,soup,aromatic,herbs', cuisine: 'vietnamese', prep_time: 30, cook_time: 180, difficulty: 3, budget: 'medium', calories: 380, servings: 4, wine_pairing: 'Bière vietnamienne', season: 'winter', recipe_json: JSON.stringify({ steps: ['Préparer bouillon: os de bœuf, anis, cannelle, gingembre', 'Mijoter 3h minimum', 'Cuire les nouilles de riz', 'Trancher le bœuf finement', 'Servir avec herbes: menthe, basilic thaï, germes'] }), ingredients_json: JSON.stringify([{ name: 'Os de bœuf', qty: '1 kg', cat: 'viande' }, { name: 'Bœuf (rumsteck)', qty: '400g', cat: 'viande' }, { name: 'Nouilles de riz', qty: '400g', cat: 'épicerie' }, { name: 'Anis étoilé', qty: '3', cat: 'épicerie' }]) },

    { id: 'arancini', name: 'Arancini siciliens', emoji: '🍚', description: 'Boulettes de risotto panées frites, mozzarella', tags: 'italian,rice,cheese,fried,comfort', cuisine: 'italian', prep_time: 45, cook_time: 15, difficulty: 3, budget: 'low', calories: 320, servings: 6, wine_pairing: 'Nero d\'Avola', is_vegetarian: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Préparer un risotto et le refroidir', 'Former des boules avec cube de mozzarella au centre', 'Paner: farine, œuf, chapelure', 'Frire jusqu\'à doré', 'Servir avec sauce tomate'] }), ingredients_json: JSON.stringify([{ name: 'Riz arborio', qty: '300g', cat: 'épicerie' }, { name: 'Mozzarella', qty: '150g', cat: 'fromage' }, { name: 'Parmesan', qty: '80g', cat: 'fromage' }, { name: 'Chapelure', qty: '150g', cat: 'épicerie' }]) },

    { id: 'tapenade', name: 'Tapenade provençale', emoji: '🫒', description: 'Purée d\'olives noires, câpres, anchois', tags: 'french,mediterranean,olives,spread,provencal', cuisine: 'french', prep_time: 15, cook_time: 0, difficulty: 1, budget: 'low', calories: 180, servings: 6, wine_pairing: 'Bandol rosé', season: 'summer', recipe_json: JSON.stringify({ steps: ['Mixer olives dénoyautées, câpres, anchois', 'Ajouter huile d\'olive progressivement', 'Assaisonner ail et thym', 'Servir avec pain grillé'] }), ingredients_json: JSON.stringify([{ name: 'Olives noires', qty: '300g', cat: 'épicerie' }, { name: 'Câpres', qty: '50g', cat: 'épicerie' }, { name: 'Anchois', qty: '50g', cat: 'poisson' }, { name: 'Huile d\'olive', qty: '5cl', cat: 'épicerie' }]) },

    { id: 'tzatziki', name: 'Tzatziki grec', emoji: '🥒', description: 'Yaourt, concombre, ail, menthe', tags: 'greek,mediterranean,yogurt,fresh,healthy', cuisine: 'greek', prep_time: 15, cook_time: 0, difficulty: 1, budget: 'low', calories: 80, servings: 6, wine_pairing: 'Assyrtiko', is_vegetarian: 1, season: 'summer', recipe_json: JSON.stringify({ steps: ['Râper et égoutter le concombre', 'Mélanger avec yaourt grec', 'Ajouter ail écrasé, huile d\'olive', 'Assaisonner menthe, sel', 'Réfrigérer 1h'] }), ingredients_json: JSON.stringify([{ name: 'Yaourt grec', qty: '500g', cat: 'crémerie' }, { name: 'Concombre', qty: '1', cat: 'légumes' }, { name: 'Ail', qty: '2 gousses', cat: 'légumes' }, { name: 'Menthe', qty: '4 feuilles', cat: 'légumes' }]) },

    { id: 'tempura', name: 'Tempura de légumes', emoji: '🍤', description: 'Légumes en beignets légers et croustillants', tags: 'japanese,asian,vegetables,fried,crispy,light', cuisine: 'japanese', prep_time: 20, cook_time: 15, difficulty: 2, budget: 'low', calories: 220, servings: 4, wine_pairing: 'Saké froid', is_vegetarian: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Préparer pâte: farine, eau glacée, œuf', 'Découper légumes: patate douce, courgette, aubergine', 'Tremper dans pâte froide', 'Frire rapidement à 180°C', 'Servir avec sauce tentsuyu'] }), ingredients_json: JSON.stringify([{ name: 'Légumes variés', qty: '400g', cat: 'légumes' }, { name: 'Farine', qty: '150g', cat: 'épicerie' }, { name: 'Eau glacée', qty: '25cl', cat: 'autre' }, { name: 'Œuf', qty: '1', cat: 'crémerie' }]) },

    { id: 'spring_rolls', name: 'Rouleaux impériaux', emoji: '🥢', description: 'Rouleaux croustillants aux légumes et vermicelles', tags: 'chinese,asian,vegetables,fried,crispy', cuisine: 'chinese', prep_time: 40, cook_time: 15, difficulty: 2, budget: 'low', calories: 180, servings: 6, wine_pairing: 'Thé vert', is_vegan: 1, season: 'all', recipe_json: JSON.stringify({ steps: ['Préparer farce: chou, carottes, vermicelles, champignons', 'Assaisonner sauce soja, gingembre', 'Rouler dans feuilles de brick', 'Frire jusqu\'à doré', 'Servir avec sauce aigre-douce'] }), ingredients_json: JSON.stringify([{ name: 'Chou chinois', qty: '300g', cat: 'légumes' }, { name: 'Carottes', qty: '2', cat: 'légumes' }, { name: 'Vermicelles', qty: '100g', cat: 'épicerie' }, { name: 'Feuilles de brick', qty: '12', cat: 'épicerie' }]) },
];

// Insert starters
const insertMeal = db.prepare(`
    INSERT OR REPLACE INTO meals (id, type, name, emoji, description, tags, cuisine, prep_time, cook_time, difficulty, budget, calories, servings, wine_pairing, cheese_pairing, season, is_vegetarian, is_vegan, is_gluten_free, recipe_json, ingredients_json)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

for (const s of starters) {
    insertMeal.run(
        s.id, 'starter', s.name, s.emoji, s.description, s.tags, s.cuisine || 'french',
        s.prep_time || 20, s.cook_time || 20, s.difficulty || 2, s.budget || 'medium',
        s.calories || 200, s.servings || 4, s.wine_pairing || null, s.cheese_pairing || null,
        s.season || 'all', s.is_vegetarian || 0, s.is_vegan || 0, s.is_gluten_free || 0,
        s.recipe_json, s.ingredients_json
    );
}

console.log(`✅ ${starters.length} starters inserted`);

// Continue in next file...
console.log('📝 Run seed-meals-mains.js next for main dishes...');

module.exports = { db, insertMeal };
